# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MI_THERMAL_INTERFACE) += mi_thermal_interface.o
# kernel private drivers/base/base.h (subsys_private / to_subsys_private)
ccflags-y += -I$(srctree)/drivers/base
# kernel private drivers/thermal/thermal_core.h
ccflags-y += -I$(srctree)/drivers/thermal
